### ISSUE TITLE
Less: dimensions expressed in rem flagged as errors

### ISSUE THREAD

**Issue by rombert** [vtst/ow#101]
With the following test file

``` css
body {
    padding-left: 2rem;   
}
```

I get an error reported at line 2: 

>  mismatched character 'e' expecting 'a'
