### ISSUE TITLE
Less: The following code issues an error

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [vtst/ow#138]
```
.ui-button, .ui-dialog .ui-dialog-titlebar-close {
  a&:hover,
  a&:active {
    color: #FFF;
  }
}
```

and should not, since this is a valid LESS syntax to produce the following code:

``` CSS
a.ui-button:hover,
a.ui-dialog .ui-dialog-titlebar-close:hover,
a.ui-button:active,
a.ui-dialog .ui-dialog-titlebar-close:active {
  color: #FFF;
}

```
