### ISSUE TITLE
Less: Parsing of '& + &'

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [vtst/ow#151]
v1.0.17 regression

``` CSS
/**
 * 1. no viable alternative at input '&'
 * 1. no viable alternative at input '+'
 */
.input-append, .input-prepend {
  & + & { /* 1 */
    padding-left: 5px;
  }
}
```
