### ISSUE TITLE
LESS: mixin calls in @keyframes statements

### ISSUE THREAD

**Issue by dtrunk90** [vtst/ow#155]
Example:

``` less
.rotation {
    from {
        -webkit-transform: rotate(0deg);
        -moz-transform: rotate(0deg);
        -ms-transform: rotate(0deg);
        -o-transform: rotate(0deg);
        transform: rotate(0deg);
    }
    to {
        -webkit-transform: rotate(359deg);
        -moz-transform: rotate(359deg);
        -ms-transform: rotate(359deg);
        -o-transform: rotate(359deg);
        transform: rotate(359deg);
    }
}

@-webkit-keyframes rotate {
    .rotation; // mismatched input '.' expecting '}'
} // missing EOF at '}'

@-moz-keyframes rotate {
    .rotation;
}

@-ms-keyframes rotate {
    .rotation;
}

@-o-keyframes rotate {
    .rotation;
}

@keyframes rotate {
    .rotation;
}
```
