### ISSUE TITLE
LESS: formatter adding space after '&'

### ISSUE THREAD

**Issue by ycfreeman** [vtst/ow#157]
is it just me or is it a bug?

it keeps adding empty space to '&' after formatting, which breaks all combinators

e.g.

``` scss
.bordered {
  &.float {
    float: left;
  }
  .top {
    margin: 5px;
  }
}
```

after format it becomes

``` scss
.bordered {
  & .float {
    float: left;
  }
  .top {
    margin: 5px;
  }
}
```

which breaks the output as it becomes

```
.bordered .float
```

instead of 

```
.bordered.float
```

it works for pseudo-classes only at the moment
