### ISSUE TITLE
Less: Parameter in parameter default value

### ISSUE THREAD

**Issue by vtst** [vtst/ow#159]
The following code generates an error for the default value of the second argument:

``` css
#test(@a, @b : @a) {
    a: @a;
    b: @b;
}
```

or even

``` css
#test(@a : @b, @b : @a) {
    a: @a;
    b: @b;
}
```
