### ISSUE TITLE
Less: variables in #-selectors

### ISSUE THREAD

**Issue by vtst** [vtst/ow#160]
The following code generates an error while it is accepted by the LESS compiler:

``` css
#bar-@{foo} {
    a: 1;
}
```
