### ISSUE TITLE
Less: No error for unspecified mixin parameter

### ISSUE THREAD

**Issue by vtst** [vtst/ow#171]
``` css
.test(@a, @b: default) {
    a: @a;
    b: @b;
}

.foo {
    .test (@b: 1);
}
```
