### ISSUE TITLE
Keyframe definition syntax not supported

### ISSUE THREAD

**Issue by atsolberg** [vtst/ow#251]
My keyframe definition compiles from less to css using other tools but is showing an error in eclipse.

``` css
@-webkit-keyframes shake-subtle {
    0%, 100% {
        -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
    }

    10%, 30%, 50%, 70%, 90% {
        -webkit-transform: translate3d(-2px, 0, 0);
                transform: translate3d(-2px, 0, 0);
    }

    20%, 40%, 60%, 80% {
        -webkit-transform: translate3d(2px, 0, 0);
                transform: translate3d(2px, 0, 0);
    }
}
```
