### ISSUE TITLE
missing RULE_NUMBER at @

### ISSUE THREAD

**Issue by freddyboucher** [vtst/ow#256]
When importing **Bootstrap less** files, I get an error **missing RULE_NUMBER at @**

<img width="655" alt="screen shot 2015-09-04 at 21 09 46" src="https://cloud.githubusercontent.com/assets/695120/9682364/5d0e2f00-5349-11e5-9ab2-0352c9560db1.png">

``` less
.calc-grid-column(@index, @class, @type) when (@type = width) and (@index > 0) {
  .col-@{class}-@{index} {
    width: percentage((@index / @grid-columns));
  }
}
```

[grid-framework.less#L47](https://github.com/twbs/bootstrap/blob/master/less/mixins/grid-framework.less#L47)

LESS plugin version 1.0.22

Cheers
