### ISSUE TITLE
Less: Mixin parameters with spaces break the outline tree and highlighting

### ISSUE THREAD

**Issue by levito** [vtst/ow#26]
I'm often using mixins like this:

``` css
.boxShadow(@params1, @params2:0 0) {
       -moz-box-shadow:@params1, @params2;
         -o-box-shadow:@params1, @params2;
    -webkit-box-shadow:@params1, @params2;
            box-shadow:@params1, @params2;
}
```

Using such mixins with parameters containing spaces breaks the outline and highlighting:

``` css
.foo { .boxShadow(0 5px 10px @black) }
.bar { .boxShadow(inset 0 0 3px @red) }
.baz { .boxShadow(0 2px 8px @black, inset 0 0 3px @red) }
```
