### ISSUE TITLE
LESS attribute from variable reports warnings.

### ISSUE THREAD

**Issue by WORMSS** [vtst/ow#270]
LESS attribute from variable reports warnings.
```less
.someclass {
    @some-data-attribute: ~"data-something"; 
    
    &[@{some-data-attribute}] {
        color: red;
    }
}
```

LESS Plugin for Eclipse shows error:
```
Multiple markers at this line
- no viable alternative at input '@' 
- mismatched input ']' expecting '}'
- no viable alternative at input ''
```

This is valid less code. It compiles correctly during ant build, and tested with an online less/css compiler.

Eclipse: `Neon 4.6.0`  
LESS Plugin for Eclipse `1.0.22`
OS: `Windows 10 Pro 64bit`
