### ISSUE TITLE
CSS custom properties

### ISSUE THREAD

**Issue by steph950** [vtst/ow#277]
Thanks for your great work.

I don't know if you have still time to work on it, but the CSS custom properties are not validated by the eclipse plugin.

`--main-bg-color:@mainBGColor;` => the double dashes are not recognized as valid during lexical analysis

`var(--main-bg-color)` => this is also not recognized as valid

But even if Eclipse considers these to be errors, the code is perfectly compiled by the less compiler.

**Comment by vobruba-martin** [comment]
I'm using this ugly workaround:

```less
:root {
  -x: ~'0;'
  ~'--main-bg-color:' @mainBGColor ~';'
  ~'--another-custom-property:' @whatever ~';'
  ;
}
body {
  background-color: ~'var(--main-bg-color)';
}
```
