### ISSUE TITLE
Less: Star-property-hack breaks code recognition

### ISSUE THREAD

**Issue by izzy** [vtst/ow#5]
When you use the star-property-hack for IE-specific behaviours it breaks the recognition for the code afterwards.

I.e. when using 2 mixins where the first is using the star hack, it won't show the second mixin in the right scope:

``` css
.mixin-1(@v) {
  property: @v;
  *zoom: 1;
}

.mixin-2(@v) {
  property: @v;
}
```

When you look at the outline, instead of the 2 mixins it will show something like 

```
+ mixin-1
-+ *
 -+ mixin-2
```
