### ISSUE TITLE
Less: Missing support for nested media queries

### ISSUE THREAD

**Issue by ghost** [vtst/ow#76]
When nesting media queries as supported by lesscss the editor highlights the syntax error: 

> mismatched input '@media' expecting '}'

example code:

``` css
#action_bar {
  height: 38px;
  padding: 12px 30px 0;
  @media only screen and (max-width: 500px){
     padding: 2px 2px 0;
     height: 31px;
  }
  letter-spacing: -4px;
  ...
```
